apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iyshg89vj-go 
  janus-idp.io/tekton: iyshg89vj-go
  backstage.io/kubernetes-id: iyshg89vj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iyshg89vj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  